// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OptixTechTest.Domain;

#nullable disable

namespace OptixTechTest.Domain.Migrations
{
    [DbContext(typeof(MoviesDbContext))]
    [Migration("20250520144705_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OptixTechTest.Domain.Models.Movie", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.PrimitiveCollection<List<string>>("Actors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.PrimitiveCollection<List<string>>("Genres")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("OriginalLanguage")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Overview")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)");

                    b.Property<decimal>("Popularity")
                        .HasColumnType("numeric");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateOnly>("ReleaseDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<decimal>("VoteAverage")
                        .HasColumnType("numeric");

                    b.Property<long>("VoteCount")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("Actors");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Actors"), "GIN");

                    b.HasIndex("Genres");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Genres"), "GIN");

                    b.HasIndex("Popularity");

                    b.HasIndex("ReleaseDate");

                    b.HasIndex("Title");

                    b.HasIndex("VoteAverage");

                    b.HasIndex("VoteCount");

                    b.ToTable("Movies");
                });
#pragma warning restore 612, 618
        }
    }
}
